from datetime import date

from schemas.document import DocumentChunk


def load_sample_chunks() -> list[DocumentChunk]:
    return [
        DocumentChunk(
            chunk_id="DOC-ANNUAL-2022-C001",
            document_id="ANNUAL-2022",
            company_id="000001.SZ",
            document_type="annual_report_note",
            title="2022 年年度报告附注",
            publish_date=date(2023, 4, 28),
            page=86,
            section="存货",
            text="公司期末存货余额较上年明显增长，主要来自原材料和库存商品增加。公司已按照成本与可变现净值孰低计提存货跌价准备。",
            source_path="data/documents/ANNUAL-2022.pdf",
        ),
        DocumentChunk(
            chunk_id="DOC-ANNUAL-2022-C002",
            document_id="ANNUAL-2022",
            company_id="000001.SZ",
            document_type="annual_report_note",
            title="2022 年年度报告附注",
            publish_date=date(2023, 4, 28),
            page=92,
            section="应收账款",
            text="公司应收账款余额增长较快，主要由于部分客户信用期延长。管理层认为坏账准备计提充分。",
            source_path="data/documents/ANNUAL-2022.pdf",
        ),
        DocumentChunk(
            chunk_id="DOC-AUDIT-2022-C001",
            document_id="AUDIT-2022",
            company_id="000001.SZ",
            document_type="audit_report",
            title="2022 年审计报告",
            publish_date=date(2023, 4, 28),
            page=4,
            section="关键审计事项",
            text="收入确认和存货跌价准备为关键审计事项。审计师执行了函证、截止性测试和存货监盘等程序。",
            source_path="data/documents/AUDIT-2022.pdf",
        ),
        DocumentChunk(
            chunk_id="DOC-INQUIRY-2023-C001",
            document_id="INQUIRY-2023",
            company_id="000001.SZ",
            document_type="regulatory_inquiry",
            title="关于示例上市公司年报事项的问询函",
            publish_date=date(2023, 5, 18),
            page=2,
            section="问题一",
            text="请公司说明存货余额大幅增长的原因、库龄结构、跌价准备计提是否充分，以及是否存在以存货调节利润的情形。",
            source_path="data/documents/INQUIRY-2023.pdf",
        ),
        DocumentChunk(
            chunk_id="DOC-NEWS-2022-C001",
            document_id="NEWS-2022-001",
            company_id="000001.SZ",
            document_type="news",
            title="示例上市公司回应存货增长",
            publish_date=date(2022, 12, 20),
            page=1,
            section="新闻正文",
            text="公司表示存货增加与订单备货有关，后续将结合市场需求变化持续评估减值风险。",
            source_path="data/documents/NEWS-2022-001.txt",
        ),
        DocumentChunk(
            chunk_id="DOC-OTHER-2022-C001",
            document_id="OTHER-2022",
            company_id="000002.SZ",
            document_type="annual_report_note",
            title="其他公司年报附注",
            publish_date=date(2023, 4, 20),
            page=50,
            section="存货",
            text="其他公司存货变化较小。",
            source_path="data/documents/OTHER-2022.pdf",
        ),
    ]
